# Example: Using ArchiveStream in your own project

FROM python:3.12-slim

WORKDIR /app

RUN pip install archivestream==0.8.5rc50
RUN archivestream install

RUN useradd -ms /bin/bash archivestream && chown -R archivestream /app











