---
apiVersion: v1
kind: Namespace
metadata:
  name: archivestream
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: archivestream
  name: archivestream
  namespace: archivestream
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: archivestream
  namespace: archivestream
spec:
  selector:
    matchLabels:
      app: archivestream
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: archivestream
    spec:
      initContainers:
      - name: init-archivestream
        image: archivestream/archivestream
        args: ['init']
        volumeMounts:
          - mountPath: /data
            name: archivestream
      containers:
        - name: archivestream
          args: ["server", "--quick-init", "0.0.0.0:8000"]
          image: archivestream/archivestream
          ports:
            - containerPort: 8000
              protocol: TCP
              name: http
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
          volumeMounts:
            - mountPath: /data
              name: archivestream
      restartPolicy: Always
      volumes:
        - name: archivestream
          persistentVolumeClaim:
            claimName: archivestream
---
apiVersion: v1
kind: Service
metadata:
  name: archivestream
  namespace: archivestream
spec:
  ports:
    - name: http
      port: 8000
  selector:
    app: archivestream
  type: LoadBalancer